window.PAPERS_DATA = {
  "filters": [
    {
      "key": "selected",
      "label": "Recent Highlights"
    },
    {
      "key": "preprint",
      "label": "Pre-print"
    },
    {
      "key": "2026",
      "label": "2026"
    },
    {
      "key": "2025",
      "label": "2025"
    },
    {
      "key": "2024",
      "label": "2024"
    },
    {
      "key": "2023",
      "label": "2023"
    },
    {
      "key": "2022",
      "label": "2022"
    },
    {
      "key": "all",
      "label": "All"
    }
  ],
  "papers": [
    {
      "id": "yan2026consistency",
      "title": "Consistency in Diffusion-Based Visual Generation: A Survey",
      "title_url": "https://www.preprints.org/frontend/manuscript/bb70c5a8337c1ff741d45d43f2392e23/download_pub",
      "authors": [
        "Song Yan",
        "Wei Zhai",
        "Chenfeng Wang",
        "Ruixuan Li",
        "Zhangping Yang",
        "Yancheng Cai",
        "Tao Zhang",
        "Ling Wang",
        "Yunwei Lan",
        "Yujie He",
        "Yang Cao",
        "Min Li",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "preprint",
      "featured": true,
      "rating": null,
      "pdf": "https://www.preprints.org/frontend/manuscript/bb70c5a8337c1ff741d45d43f2392e23/download_pub",
      "project": "https://github.com/Shawn-CodeDev/Awesome-Consistency-Diffusion-Visual-Generation",
      "code": "",
      "image": "./Wei Zhai_files/yan2026consistency.png",
      "video": "",
      "venue_html": "Preprints.org, 2026\n            <br><span class=\"paper-note\">Survey paper on consistency in diffusion-based visual generation.</span>",
      "note": "Survey paper on consistency in diffusion-based visual generation.",
      "description": "A survey that organizes consistency in diffusion-based visual generation into external, internal, and normative agreement relations, covering methods, benchmarks, evaluation protocols, and open problems across image, video, and 3D generation.",
      "bibtex": "@article{yan2026consistency,\n  title={Consistency in Diffusion-Based Visual Generation: A Survey},\n  author={Yan, Song and Zhai, Wei and Wang, Chenfeng and Li, Ruixuan and Yang, Zhangping and Cai, Yancheng and Zhang, Tao and Wang, Ling and Lan, Yunwei and He, Yujie and Cao, Yang and Li, Min and Zha, Zheng-Jun},\n  journal={Preprints.org},\n  year={2026}\n}"
    },
    {
      "id": "zhang2026end",
      "title": "End-to-End Spatial-Temporal Transformer for Real-time 4D HOI Reconstruction",
      "title_url": "https://arxiv.org/abs/2603.14435",
      "authors": [
        "Haoyu Zhang",
        "Wei Zhai",
        "Yuhang Yang",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "preprint",
      "featured": true,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2603.14435",
      "project": "https://nianheng.github.io/THO-project/",
      "code": "",
      "image": "",
      "video": "./Wei Zhai_files/zhang2026end.mp4",
      "venue_html": "Arxiv",
      "note": "",
      "description": "An end-to-end Spatial-Temporal Transformer that achieves real-time (31.5 FPS), physically plausible 4D human-object reconstruction from a single video without test-time optimization.",
      "bibtex": "@article{zhang2026end,\n  title={End-to-End Spatial-Temporal Transformer for Real-time 4D HOI Reconstruction},\n  author={Zhang, Haoyu and Zhai, Wei and Yang, Yuhang and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2603.14435},\n  year={2026}\n}"
    },
    {
      "id": "yu2026explore",
      "title": "EXPLORE-Bench: Egocentric Scene Prediction with Long-Horizon Reasoning",
      "title_url": "https://arxiv.org/abs/2603.09731",
      "authors": [
        "Chengjun Yu",
        "Xuhan Zhu",
        "Chaoqun Du",
        "Pengfei Yu",
        "Wei Zhai",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": true,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2603.09731",
      "project": "https://jackyu6.github.io/EXPLORE-Page/",
      "code": "",
      "image": "./Wei Zhai_files/yu2026explore.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ECCV 2026</span>",
      "note": "",
      "description": "A benchmark for egocentric scene prediction that evaluates long-horizon physical reasoning in multimodal large language models from first-person observations.",
      "bibtex": "@article{yu2026explore,\n  title={EXPLORE-Bench: Egocentric Scene Prediction with Long-Horizon Reasoning},\n  author={Yu, Chengjun and Zhu, XuHan and Du, Chaoqun and Yu, Pengfei and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2603.09731},\n  year={2026}\n}"
    },
    {
      "id": "valueanchoredgrouppolicyoptimiza",
      "title": "Value-Anchored Group Policy Optimization for Flow Models",
      "title_url": "",
      "authors": [
        "Yawen Shao",
        "Jie Xiao",
        "Kai Zhu",
        "Yu Liu",
        "Wei Zhai",
        "Yuhang Yang",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": null,
      "section": "preprint",
      "featured": false,
      "rating": null,
      "pdf": "",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/shao2025value.png",
      "video": "",
      "venue_html": "Arxiv",
      "note": "",
      "description": "",
      "bibtex": ""
    },
    {
      "id": "yang2025videogen",
      "title": "VideoGen-Eval: Agent-based System for Video Generation Evaluation",
      "title_url": "https://arxiv.org/abs/2503.23452",
      "authors": [
        "Yuhang Yang",
        "Shangkun Sun",
        "Hongxiang Li",
        "Ke Fan",
        "Ailing Zeng",
        "Feilin Han",
        "Wei Zhai",
        "Wei Liu",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "preprint",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2503.23452",
      "project": "",
      "code": "https://github.com/AILab-CVC/VideoGen-Eval",
      "image": "./Wei Zhai_files/yang2025videogen.png",
      "video": "",
      "venue_html": "Arxiv",
      "note": "",
      "description": "",
      "bibtex": "@article{yang2025videogen,\n  title={VideoGen-Eval: Agent-based System for Video Generation Evaluation},\n  author={Yang, Yuhang and Fan, Ke and Sun, Shangkun and Li, Hongxiang and Zeng, Ailing and Han, FeiLin and Zhai, Wei and Liu, Wei and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2503.23452},\n  year={2025}\n}"
    },
    {
      "id": "luo2024visual",
      "title": "Visual-Geometric Collaborative Guidance for Affordance Learning",
      "title_url": "https://arxiv.org/pdf/2410.11363",
      "authors": [
        "Hongchen Luo",
        "Wei Zhai",
        "Jiao Wang",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "preprint",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/pdf/2410.11363",
      "project": "",
      "code": "https://github.com/lhc1224/VCR-Net",
      "image": "./Wei Zhai_files/luo2024visual.png",
      "video": "",
      "venue_html": "Arxiv\n            <br><span class=\"paper-note\">Journal version of \"Leverage Interactive Affinity for Affordance Learning\" (CVPR 2023)</span>",
      "note": "Journal version of \"Leverage Interactive Affinity for Affordance Learning\" (CVPR 2023)",
      "description": "",
      "bibtex": "@article{luo2024visual,\n    title={Visual-Geometric Collaborative Guidance for Affordance Learning},\n    author={Luo, Hongchen and Zhai, Wei and Wang, Jiao and Cao, Yang and Zha, Zheng-Jun},\n    journal={arXiv preprint arXiv:2410.11363},\n    year={2024}\n    }"
    },
    {
      "id": "liu2024grounding",
      "title": "Grounding 3D Scene Affordance From Egocentric Interactions",
      "title_url": "https://arxiv.org/pdf/2409.19650",
      "authors": [
        "Cuiyu Liu",
        "Wei Zhai",
        "Yuhang Yang",
        "Hongchen Luo",
        "Sen Liang",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "preprint",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/pdf/2409.19650",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/liu2024grounding.png",
      "video": "",
      "venue_html": "Arxiv",
      "note": "",
      "description": "",
      "bibtex": "@article{liu2024grounding,\n    title={Grounding 3D Scene Affordance From Egocentric Interactions},\n    author={Liu, Cuiyu and Zhai, Wei and Yang, Yuhang and Luo, Hongchen and Liang, Sen and Cao, Yang and Zha, Zheng-Jun},\n    journal={arXiv preprint arXiv:2409.19650},\n    year={2024}\n    }"
    },
    {
      "id": "fang2024vivid",
      "title": "ViViD: Video Virtual Try-on using Diffusion Models",
      "title_url": "https://arxiv.org/abs/2405.11794",
      "authors": [
        "Zixun Fang",
        "Wei Zhai",
        "Aimin Su",
        "Hongliang Song",
        "Kai Zhu",
        "Mao Wang",
        "Yu Chen",
        "Zhiheng Liu",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "preprint",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2405.11794",
      "project": "",
      "code": "https://github.com/alibaba-yuanjing-aigclab/ViViD",
      "image": "./Wei Zhai_files/fang2024vivid.gif",
      "video": "",
      "venue_html": "Arxiv",
      "note": "",
      "description": "",
      "bibtex": "@article{fang2024vivid,\n    title={ViViD: Video Virtual Try-on using Diffusion Models},\n    author={Fang, Zixun and Zhai, Wei and Su, Aimin and Song, Hongliang and Zhu, Kai and Wang, Mao and Chen, Yu and Liu, Zhiheng and Cao, Yang and Zha, Zheng-Jun},\n    journal={arXiv preprint arXiv:2405.11794},\n    year={2024}\n    }"
    },
    {
      "id": "luo2024intention",
      "title": "Intention-driven Ego-to-Exo Video Generation",
      "title_url": "https://arxiv.org/abs/2403.09194",
      "authors": [
        "Hongchen Luo",
        "Kai Zhu",
        "Wei Zhai",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "preprint",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2403.09194",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/luo2024intention.png",
      "video": "",
      "venue_html": "Arxiv",
      "note": "",
      "description": "",
      "bibtex": "@article{luo2024intention,\n    title={Intention-driven Ego-to-Exo Video Generation},\n    author={Luo, Hongchen and Zhu, Kai and Zhai, Wei and Cao, Yang},\n    journal={arXiv preprint arXiv:2403.09194},\n    year={2024}\n    }"
    },
    {
      "id": "skyfindalargescalebenchmarkunvei",
      "title": "SkyFind: A Large-Scale Benchmark Unveiling Referring Expression Comprehension for UAV",
      "title_url": "https://www.computer.org/csdl/journal/tp/5555/01/11475181/2fuLQIZcQMw",
      "authors": [
        "Kunyu Wang",
        "Guanbo Wu",
        "Xueyang Fu",
        "Xingbo Wang",
        "Kean Liu",
        "Xin Lu",
        "Chengjie Ge",
        "Wei Zhai",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": true,
      "rating": null,
      "pdf": "https://www.computer.org/csdl/journal/tp/5555/01/11475181/2fuLQIZcQMw",
      "project": "",
      "code": "https://github.com/wangkunyu241/SkyFind",
      "image": "./Wei Zhai_files/wang2026skyfind.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-PAMI</span>",
      "note": "",
      "description": "Establishes the first formal definition of UAV-based REC and provides SkyFind—a large-scale dataset with one million high-quality pairs—to address the unique challenges of aerial target localization.",
      "bibtex": ""
    },
    {
      "id": "wu2026event",
      "title": "Event-based Visual Deformation Measurement",
      "title_url": "https://arxiv.org/abs/2602.14376",
      "authors": [
        "Yuliang Wu",
        "Wei Zhai*",
        "Yuxin Cui",
        "Tiesong Zhao",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": true,
      "rating": "highlight",
      "pdf": "https://arxiv.org/abs/2602.14376",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wu2026event.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2026</span>",
      "note": "",
      "description": "An event-frame fusion framework featuring Affine Invariant Simplicial modeling that achieves robust long-term dense deformation tracking while using only 18.9% of the resources required by high-speed video methods.",
      "bibtex": "@article{wu2026event,\n  title={Event-based Visual Deformation Measurement},\n  author={Wu, Yuliang and Zhai, Wei and Cui, Yuxin and Zhao, Tiesong and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2602.14376},\n  year={2026}\n}"
    },
    {
      "id": "yang2026gloria",
      "title": "Gloria: Consistent Character Video Generation via Content Anchors",
      "title_url": "https://arxiv.org/abs/2603.29931",
      "authors": [
        "Yuhang Yang",
        "Fan Zhang",
        "Huaijin Pi",
        "Shuai Guo",
        "Guowei Xu",
        "Wei Zhai*",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": true,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2603.29931",
      "project": "https://yyvhang.github.io/Gloria_Page/",
      "code": "",
      "image": "",
      "video": "./Wei Zhai_files/yang2026gloria.mp4",
      "venue_html": "In <span class=\"venue-name\">CVPR 2026</span>",
      "note": "",
      "description": "Proposes a compact anchor-frame representation to generate high-quality, 10-minute+ character videos with superior identity preservation and multi-view appearance consistency.",
      "bibtex": "@article{yang2026gloria,\n  title={Gloria: Consistent Character Video Generation via Content Anchors},\n  author={Yang, Yuhang and Zhang, Fan and Pi, Huaijin and Guo, Shuai and Xu, Guowei and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2603.29931},\n  year={2026}\n}"
    },
    {
      "id": "zhang2026mate",
      "title": "MatE: Material Extraction from Single-Image via Geometric Prior",
      "title_url": "https://arxiv.org/abs/2512.18312",
      "authors": [
        "Zeyu Zhang",
        "Wei Zhai*",
        "Jian Yang",
        "Yang Cao*"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2512.18312",
      "project": "https://tiptoehigherz.github.io/Material-Extraction/",
      "code": "",
      "image": "./Wei Zhai_files/zhang2026mate.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2026</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{zhang2025mate,\n  title={MatE: Material Extraction from Single-Image via Geometric Prior},\n  author={Zhang, Zeyu and Zhai, Wei and Yang, Jian and Cao, Yang},\n  journal={arXiv preprint arXiv:2512.18312},\n  year={2025}\n}"
    },
    {
      "id": "unsupervised3dmotionestimationus",
      "title": "Unsupervised 3d Motion Estimation Using Event Camera",
      "title_url": "",
      "authors": [
        "Han Han",
        "Wei Zhai*",
        "Tiesong Zhao",
        "Bin Li",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": false,
      "rating": null,
      "pdf": "",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/han2026unsupervised.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2026</span>",
      "note": "",
      "description": "",
      "bibtex": ""
    },
    {
      "id": "yang2026wemmu",
      "title": "WeMMU: Enhanced Bridging of Vision-Language Models and Diffusion Models via Noisy Query Tokens",
      "title_url": "https://arxiv.org/abs/2512.02536",
      "authors": [
        "Jian Yang",
        "Dacheng Yin",
        "Xiaoxuan He",
        "Yong Li",
        "Fengyun Rao",
        "Jing Lyu",
        "Wei Zhai",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2512.02536",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/yang2026wemmu.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2026</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{yang2025wemmu,\n  title={WeMMU: Enhanced Bridging of Vision-Language Models and Diffusion Models via Noisy Query Tokens},\n  author={Yang, Jian and Yin, Dacheng and He, Xiaoxuan and Li, Yong and Rao, Fengyun and Lyu, Jing and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2512.02536},\n  year={2025}\n}"
    },
    {
      "id": "diffusionguidedchainofvisionforl",
      "title": "Diffusion Guided Chain-of-Vision for Large Autoregressive Vision Models",
      "title_url": "",
      "authors": [
        "Xinyang Wang",
        "Kecheng Zheng",
        "Minfeng Zhu",
        "Wei Wu",
        "Fan Lu",
        "Wei Zhai",
        "Wei Chen"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": false,
      "rating": null,
      "pdf": "",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wang2026diffusion.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2026</span>",
      "note": "",
      "description": "",
      "bibtex": ""
    },
    {
      "id": "chen2025event",
      "title": "Event Signal Filtering via Probability Flux Estimation",
      "title_url": "https://arxiv.org/abs/2504.07503",
      "authors": [
        "Jinze Chen",
        "Wei Zhai*",
        "Yang Cao",
        "Bin Li",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2504.07503",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/chen2025event.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2026</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{chen2025event,\ntitle={Event Signal Filtering via Probability Flux Estimation},\nauthor={Chen, Jinze and Zhai, Wei and Cao, Yang and Li, Bin and Zha, Zheng-Jun},\njournal={arXiv preprint arXiv:2504.07503},\nyear={2025}\n}"
    },
    {
      "id": "han2025touch",
      "title": "TOUCH: Text-guided Controllable Generation of Free-Form Hand-Object Interactions",
      "title_url": "https://arxiv.org/abs/2510.14874",
      "authors": [
        "Guangyi Han#",
        "Wei Zhai#",
        "Yuhang Yang",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": true,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2510.14874",
      "project": "https://guangyid.github.io/hoi123touch/",
      "code": "",
      "image": "./Wei Zhai_files/han2026touch.gif",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICLR 2026</span>",
      "note": "",
      "description": "Extends HOI generation from fixed grasping to diverse free-form interactions (e.g., pushing, poking) by introducing the large-scale WildO2 dataset and the TOUCH diffusion-based framework for fine-grained semantic control.",
      "bibtex": "@article{han2025touch,\n  title={TOUCH: Text-guided Controllable Generation of Free-Form Hand-Object Interactions},\n  author={Han, Guangyi and Zhai, Wei and Yang, Yuhang and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2510.14874},\n  year={2025}\n}"
    },
    {
      "id": "chen2026unbias",
      "title": "Unbiased Gradient Estimation for Event Binning via Functional Backpropagation",
      "title_url": "https://arxiv.org/abs/2602.12590",
      "authors": [
        "Jinze Chen",
        "Wei Zhai*",
        "Han Han",
        "Tiankai Ma",
        "Yang Cao",
        "Bin Li",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2602.12590",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/chen2026unbias.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICLR 2026</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{chen2026unbiased,\n  title={Unbiased Gradient Estimation for Event Binning via Functional Backpropagation},\n  author={Chen, Jinze and Zhai, Wei and Han, Han and Ma, Tiankai and Cao, Yang and Li, Bin and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2602.12590},\n  year={2026}\n}"
    },
    {
      "id": "wu2025alitok",
      "title": "Towards Sequence Modeling Alignment between Tokenizer and Autoregressive Model",
      "title_url": "https://arxiv.org/abs/2506.05289",
      "authors": [
        "Pingyu Wu",
        "Kai Zhu",
        "Yu Liu",
        "Longxiang Tang",
        "Jian Yang",
        "Yansong Peng",
        "Wei Zhai",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2026,
      "section": "2026",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2506.05289",
      "project": "",
      "code": "https://github.com/ali-vilab/alitok",
      "image": "./Wei Zhai_files/wu2025alitok.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICLR 2026</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wu2025alitok,\n  title={AliTok: Towards Sequence Modeling Alignment between Tokenizer and Autoregressive Model},\n  author={Wu, Pingyu and Zhu, Kai and Liu, Yu and Tang, Longxiang and Yang, Jian and Peng, Yansong and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2506.05289},\n  year={2025}\n}"
    },
    {
      "id": "emateventorientedmambaforegocent",
      "title": "E-MaT: Event-oriented Mamba for Egocentric Point Tracking",
      "title_url": "",
      "authors": [
        "Han Han",
        "Wei Zhai*",
        "Baocai Yin",
        "Yang Cao",
        "Bin Li",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/han2025e.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">AAAI 2025</span>",
      "note": "",
      "description": "",
      "bibtex": ""
    },
    {
      "id": "wang2025towards",
      "title": "Towards Better De-raining Generalization via Rainy Characteristics Memorization and Replay",
      "title_url": "https://arxiv.org/abs/2506.02477",
      "authors": [
        "Kunyu Wang",
        "Xueyang Fu",
        "Chengzhi Cao",
        "Chengjie Ge",
        "Wei Zhai",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2506.02477",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wang2025towards.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-NNLS</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wang2025towards,\n  title={Towards Better De-raining Generalization via Rainy Characteristics Memorization and Replay},\n  author={Wang, Kunyu and Fu, Xueyang and Cao, Chengzhi and Ge, Chengjie and Zhai, Wei and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2506.02477},\n  year={2025}\n}"
    },
    {
      "id": "liao2024ef-bib-list",
      "title": "EF-3DGS: Event-Aided Free-Trajectory 3D Gaussian Splatting",
      "title_url": "https://arxiv.org/pdf/2410.15392",
      "authors": [
        "Bohao Liao",
        "Wei Zhai*",
        "Zengyu Wan",
        "Zhixin Cheng",
        "Wenfei Yang",
        "Yang Cao",
        "Tianzhu Zhang",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": "spotlight",
      "pdf": "https://arxiv.org/pdf/2410.15392",
      "project": "",
      "code": "https://lbh666.github.io/ef-3dgs/",
      "image": "./Wei Zhai_files/liao2024ef.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">NeurIPS 2025</span>",
      "note": "",
      "description": "",
      "bibtex": ""
    },
    {
      "id": "fang2025panoramic",
      "title": "ViewPoint: Panoramic Video Generation with Pretrained Diffusion Models",
      "title_url": "https://arxiv.org/abs/2506.23513",
      "authors": [
        "Zixun Fang",
        "Kai Zhu",
        "Zhiheng Liu",
        "Yu Liu",
        "Wei Zhai",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2506.23513",
      "project": "https://becauseimbatman0.github.io/ViewPoint",
      "code": "",
      "image": "./Wei Zhai_files/fang2025panoramic.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">NeurIPS 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{fang2025panoramic,\n  title={Panoramic Video Generation with Pretrained Diffusion Models},\n  author={Fang, Zixun and Zhu, Kai and Liu, Zhiheng and Liu, Yu and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2506.23513},\n  year={2025}\n}"
    },
    {
      "id": "wang2025paid",
      "title": "PAID: Pairwise Angular-Invariant Decomposition for Continual Test-Time Adaptation",
      "title_url": "https://arxiv.org/abs/2506.02453",
      "authors": [
        "Kunyu Wang",
        "Xueyang Fu",
        "Yuanfei Bao",
        "Chengjie Ge",
        "Chengzhi Cao",
        "Wei Zhai",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2506.02453",
      "project": "",
      "code": "https://github.com/wangkunyu241/PAID",
      "image": "./Wei Zhai_files/wang2025paid.jpg",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">NeurIPS 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wang2025paid,\n  title={PAID: Pairwise Angular-Invariant Decomposition for Continual Test-Time Adaptation},\n  author={Wang, Kunyu and Fu, Xueyang and Bao, Yuanfei and Ge, Chengjie and Cao, Chengzhi and Zhai, Wei and Zha, Zheng-Jun},\n  journal={arXiv preprint arXiv:2506.02453},\n  year={2025}\n}"
    },
    {
      "id": "huang2024leverage",
      "title": "Learning Object Affordance Ranking with Task Context",
      "title_url": "https://arxiv.org/abs/2411.16082",
      "authors": [
        "Haojie Huang",
        "Hongchen Luo*",
        "Wei Zhai*",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": "best student paper",
      "pdf": "https://arxiv.org/abs/2411.16082",
      "project": "",
      "code": "https://wpy1999.github.io/IV-VAE/",
      "image": "./Wei Zhai_files/huang2024leverage.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ACM MM 2025 MSMA Workshop</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{huang2024leverage,\ntitle={Leverage Task Context for Object Affordance Ranking},\nauthor={Huang, Haojie and Luo, Hongchen and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\njournal={arXiv preprint arXiv:2411.16082},\nyear={2024}\n}"
    },
    {
      "id": "yang2025sigman",
      "title": "SIGMAN: Scaling 3D Human Gaussian Generation with Millions of Assets",
      "title_url": "https://arxiv.org/abs/2504.06982",
      "authors": [
        "Yuhang Yang",
        "Fengqi Liu",
        "Yixing Lu",
        "Qin Zhao",
        "Pingyu Wu",
        "Wei Zhai*",
        "Ran Yi",
        "Yang Cao",
        "Lizhuang Ma",
        "Zheng-Jun Zha",
        "Junting Dong*"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2504.06982",
      "project": "",
      "code": "https://yyvhang.github.io/SIGMAN_3D/",
      "image": "./Wei Zhai_files/yang2025sigman.gif",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICCV 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{yang2025sigman,\n  title={SIGMAN: Scaling 3D Human Gaussian Generation with Millions of Assets},\n  author={Yang, Yuhang and Liu, Fengqi and Lu, Yixing and Zhao, Qin and Wu, Pingyu and Zhai, Wei and Yi, Ran and Cao, Yang and Ma, Lizhuang and Zha, Zheng-Jun and others},\n  journal={arXiv preprint arXiv:2504.06982},\n  year={2025}\n}"
    },
    {
      "id": "yu2025hero",
      "title": "HERO: Human Reaction Generation from Videos",
      "title_url": "https://arxiv.org/abs/2503.08270",
      "authors": [
        "Chengjun Yu",
        "Wei Zhai*",
        "Yuhang Yang",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2503.08270",
      "project": "",
      "code": "https://jackyu6.github.io/HERO/",
      "image": "./Wei Zhai_files/yu2025hero.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICCV 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{yu2025hero,\ntitle={HERO: Human Reaction Generation from Videos},\nauthor={Yu, Chengjun and Zhai, Wei and Yang, Yuhang and Cao, Yang and Zha, Zheng-Jun},\njournal={arXiv preprint arXiv:2503.08270},\nyear={2025}\n}"
    },
    {
      "id": "han2024event",
      "title": "MATE: Motion-Augmented Temporal Consistency for Event-based Point Tracking",
      "title_url": "https://arxiv.org/abs/2412.01300",
      "authors": [
        "Han Han",
        "Wei Zhai*",
        "Yang Cao",
        "Bin Li",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2412.01300",
      "project": "",
      "code": "https://hh-xiaohu.github.io/Ev-TAP/",
      "image": "./Wei Zhai_files/han2024event.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICCV 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{han2024event,\ntitle={Event-Based Tracking Any Point with Motion-Augmented Temporal Consistency},\nauthor={Han, Han and Zhai, Wei and Cao, Yang and Li, Bin and Zha, Zheng-jun},\njournal={arXiv preprint arXiv:2412.01300},\nyear={2024}\n}"
    },
    {
      "id": "wan2025emotive",
      "title": "EMoTive: Event-guided Trajectory Modeling for 3D Motion Estimation",
      "title_url": "https://arxiv.org/abs/2503.11371",
      "authors": [
        "Zengyu Wan",
        "Wei Zhai*",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2503.11371",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wan2025emotive.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICCV 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wan2025emotive,\n  title={EMoTive: Event-guided Trajectory Modeling for 3D Motion Estimation},\n  author={Wan, Zengyu and Zhai, Wei and Cao, Yang and Zha, Zhengjun},\n  journal={arXiv preprint arXiv:2503.11371},\n  year={2025}\n}"
    },
    {
      "id": "zhang2024pear",
      "title": "PEAR: Phrase-Based Hand-Object Interaction Anticipation",
      "title_url": "https://arxiv.org/pdf/2407.21510",
      "authors": [
        "Zichen Zhang",
        "Hongchen Luo",
        "Wei Zhai",
        "Yang Cao",
        "Yu Kang"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/pdf/2407.21510",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhang2024pear.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">SCIENCE CHINA Information Sciences (SCIS)</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{zhang2024pear,\n    title={PEAR: Phrase-Based Hand-Object Interaction Anticipation},\n    author={Zhang, Zichen and Luo, Hongchen and Zhai, Wei and Cao, Yang and Kang, Yu},\n    journal={arXiv preprint arXiv:2407.21510},\n    year={2024}\n    }"
    },
    {
      "id": "wu2025brat",
      "title": "BRAT: Bidirectional Relative Positional Attention Transformer for Event-based Eye tracking",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2025W/EventVision/papers/Wu_BRAT_Bidirectional_Relative_Positional_Attention_Transformer_for_Event-based_Eye_tracking_CVPRW_2025_paper.pdf",
      "authors": [
        "Yuliang Wu",
        "Han Han",
        "Jinze Chen",
        "Wei Zhai*",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": "1st place challenge",
      "pdf": "https://openaccess.thecvf.com/content/CVPR2025W/EventVision/papers/Wu_BRAT_Bidirectional_Relative_Positional_Attention_Transformer_for_Event-based_Eye_tracking_CVPRW_2025_paper.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wu2025brat.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2025 Workshop</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{wu2025brat,\n  title={BRAT: Bidirectional Relative Positional Attention Transformer for Event-based Eye tracking},\n  author={Wu, Yuliang and Han, Han and Chen, Jinze and Zhai, Wei and Cao, Yang and Zha, Zheng-jun},\n  booktitle={Proceedings of the Computer Vision and Pattern Recognition Conference},\n  pages={5136--5144},\n  year={2025}\n}"
    },
    {
      "id": "lu2024benchmarking",
      "title": "Benchmarking Large Vision-Language Models via Directed Scene Graph for Comprehensive Image Captioning",
      "title_url": "https://arxiv.org/abs/2412.08614",
      "authors": [
        "Fan Lu",
        "Wei Wu",
        "Kecheng Zheng*",
        "Shuailei Ma",
        "Biao Gong",
        "Jiawei Liu",
        "Wei Zhai*",
        "Yang Cao",
        "Yujun Shen",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2412.08614",
      "project": "",
      "code": "https://github.com/LuFan31/CompreCap",
      "image": "./Wei Zhai_files/lu2024benchmarking.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{lu2024benchmarking,\n    title={Benchmarking Large Vision-Language Models via Directed Scene Graph for Comprehensive Image Captioning},\n    author={Lu, Fan and Wu, Wei and Zheng, Kecheng and Ma, Shuailei and Gong, Biao and Liu, Jiawei and Zhai, Wei and Cao, Yang and Shen, Yujun and Zha, Zheng-Jun},\n    journal={arXiv preprint arXiv:2412.08614},\n    year={2024}\n    }"
    },
    {
      "id": "shao2024great",
      "title": "GREAT: Geometry-Intention Collaborative Inference for Open-Vocabulary 3D Object Affordance Grounding",
      "title_url": "https://arxiv.org/abs/2411.19626",
      "authors": [
        "Yawen Shao",
        "Wei Zhai*",
        "Yuhang Yang",
        "Hongchen Luo",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2411.19626",
      "project": "",
      "code": "https://yawen-shao.github.io/GREAT/",
      "image": "./Wei Zhai_files/shao2024great.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{shao2024great,\ntitle={GREAT: Geometry-Intention Collaborative Inference for Open-Vocabulary 3D Object Affordance Grounding},\nauthor={Shao, Yawen and Zhai, Wei and Yang, Yuhang and Luo, Hongchen and Cao, Yang and Zha, Zheng-Jun},\njournal={arXiv preprint arXiv:2411.19626},\nyear={2024}\n}"
    },
    {
      "id": "wu2024improved",
      "title": "Improved Video VAE for Latent Video Diffusion Model",
      "title_url": "https://arxiv.org/abs/2411.06449",
      "authors": [
        "Pingyu Wu",
        "Kai Zhu*",
        "Yu Liu",
        "Liming Zhao",
        "Wei Zhai*",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2411.06449",
      "project": "",
      "code": "https://wpy1999.github.io/IV-VAE/",
      "image": "./Wei Zhai_files/wu2024improved.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wu2024improved,\ntitle={Improved Video VAE for Latent Video Diffusion Model},\nauthor={Wu, Pingyu and Zhu, Kai and Liu, Yu and Zhao, Liming and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\njournal={arXiv preprint arXiv:2411.06449},\nyear={2024}\n}"
    },
    {
      "id": "yang2024mmar",
      "title": "MMAR: Towards Lossless Multi-Modal Auto-Regressive Prababilistic Modeling",
      "title_url": "https://arxiv.org/pdf/2410.10798",
      "authors": [
        "Jian Yang",
        "Dacheng Yin",
        "Yizhou Zhou",
        "Fengyun Rao",
        "Wei Zhai",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/pdf/2410.10798",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/yang2024mmar.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2025</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{yang2024mmar,\n    title={MMAR: Towards Lossless Multi-Modal Auto-Regressive Prababilistic Modeling},\n    author={Yang, Jian and Yin, Dacheng and Zhou, Yizhou and Rao, Fengyun and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\n    journal={arXiv preprint arXiv:2410.10798},\n    year={2024}\n    }"
    },
    {
      "id": "efficienttesttimeadaptiveobjectd",
      "title": "Efficient Test-time Adaptive Object Detection via Sensitivity-Guided Pruning",
      "title_url": "",
      "authors": [
        "Kunyu Wang",
        "Xueyang Fu",
        "Xin Lu",
        "Chengjie Ge",
        "Chengzhi Cao",
        "Wei Zhai",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": "oral",
      "pdf": "",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wang2025efficient.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2025</span>",
      "note": "",
      "description": "",
      "bibtex": ""
    },
    {
      "id": "deng2024vmad",
      "title": "VMAD: Visual-enhanced Multimodal Large Language Model for Zero-Shot Anomaly Detection",
      "title_url": "https://arxiv.org/pdf/2409.20146",
      "authors": [
        "Huilin Deng",
        "Hongchen Luo",
        "Wei Zhai",
        "Yang Cao",
        "Yu Kang"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/pdf/2409.20146",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/deng2024vmad.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-ASE</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{deng2024vmad,\n    title={VMAD: Visual-enhanced Multimodal Large Language Model for Zero-Shot Anomaly Detection},\n    author={Deng, Huilin and Luo, Hongchen and Zhai, Wei and Cao, Yang and Kang, Yu},\n    journal={arXiv preprint arXiv:2409.20146},\n    year={2024}\n    }"
    },
    {
      "id": "lu2023likelihood",
      "title": "Likelihood-Aware Semantic Alignment for Full-Spectrum Out-of-Distribution Detection",
      "title_url": "https://arxiv.org/abs/2312.01732",
      "authors": [
        "Fan Lu",
        "Kai Zhu",
        "Kecheng Zheng",
        "Wei Zhai",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2025,
      "section": "2025",
      "featured": false,
      "rating": null,
      "pdf": "https://arxiv.org/abs/2312.01732",
      "project": "",
      "code": "https://github.com/LuFan31/LSA",
      "image": "./Wei Zhai_files/lu2023likelihood.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">Journal of Intelligent Computing and Networking</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{lu2023likelihood,\n    title={Likelihood-Aware Semantic Alignment for Full-Spectrum Out-of-Distribution Detection},\n    author={Lu, Fan and Zhu, Kai and Zheng, Kecheng and Zhai, Wei and Cao, Yang},\n    journal={arXiv preprint arXiv:2312.01732},\n    year={2023}\n    }"
    },
    {
      "id": "yang2024egochoir",
      "title": "EgoChoir: Capturing 3D Human-Object Interaction Regions from Egocentric Views",
      "title_url": "https://openreview.net/pdf?id=ea4oxkiMP7",
      "authors": [
        "Yuhang Yang",
        "Wei Zhai*",
        "Chengfeng Wang",
        "Chengjun Yu",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": null,
      "pdf": "https://openreview.net/pdf?id=ea4oxkiMP7",
      "project": "",
      "code": "https://yyvhang.github.io/EgoChoir/",
      "image": "./Wei Zhai_files/yang2024egochoir.gif",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">NeurIPS 2024</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{yang2024egochoir,\n    title={EgoChoir: Capturing 3D Human-Object Interaction Regions from Egocentric Views},\n    author={Yang, Yuhang and Zhai, Wei and Wang, Chengfeng and Yu, Chengjun and Cao, Yang and Zha, Zheng-Jun},\n    journal={arXiv preprint arXiv:2405.13659},\n    year={2024}\n    }"
    },
    {
      "id": "unidenseunleashingdiffusionmodel",
      "title": "UniDense: Unleashing Diffusion Models with Meta-Routers for Universal Few-Shot Dense Prediction",
      "title_url": "https://dl.acm.org/doi/pdf/10.1145/3664647.3680831",
      "authors": [
        "Lintao Dong",
        "Wei Zhai*",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": null,
      "pdf": "https://dl.acm.org/doi/pdf/10.1145/3664647.3680831",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/dong2024unidense.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ACM MM 2024</span>",
      "note": "",
      "description": "",
      "bibtex": ""
    },
    {
      "id": "wan2023event",
      "title": "Event-based Optical Flow via Transforming into Motion-dependent View",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/10612786/",
      "authors": [
        "Zengyu Wan",
        "Yang Wang",
        "Wei Zhai*",
        "Ganchao Tan",
        "Yang Cao",
        "Zheng-Jun Zha*"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/10612786/",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wan2023event.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-IP</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wan2024event,\n    title={Event-based Optical Flow via Transforming into Motion-dependent View},\n    author={Wan, Zengyu and Wang, Yang and Wei, Zhai and Tan, Ganchao and Cao, Yang and Zha, Zheng-Jun},\n    journal={IEEE Transactions on Image Processing},\n    year={2024},\n    publisher={IEEE}\n    }"
    },
    {
      "id": "zhang2023bidirectional",
      "title": "Bidirectional Progressive Transformer for Interaction Intention Anticipation",
      "title_url": "https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/07631.pdf",
      "authors": [
        "Zichen Zhang",
        "Hongchen Luo",
        "Wei Zhai*",
        "Yang Cao",
        "Yu Kang"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": null,
      "pdf": "https://www.ecva.net/papers/eccv_2024/papers_ECCV/papers/07631.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhang2023bidirectional.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ECCV 2024</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{zhang2024bidirectional,\n    title={Bidirectional Progressive Transformer for Interaction Intention Anticipation},\n    author={Zhang, Zichen and Luo, Hongchen and Zhai, Wei and Cao, Yang and Kang, Yu},\n    journal={arXiv preprint arXiv:2405.05552},\n    year={2024}\n    }"
    },
    {
      "id": "wu2024event",
      "title": "Event-based Asynchronous HDR Imaging by Temporal Incident Light Modulation",
      "title_url": "https://opg.optica.org/oe/fulltext.cfm?uri=oe-32-11-18527&id=549921",
      "authors": [
        "Yuliang Wu",
        "Ganchao Tan",
        "Jinze Chen",
        "Wei Zhai*",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": null,
      "pdf": "https://opg.optica.org/oe/fulltext.cfm?uri=oe-32-11-18527&id=549921",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wu2024event.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">Optics Express</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wu2024event,\n    title={Event-based asynchronous HDR imaging by temporal incident light modulation},\n    author={Wu, Yuliang and Tan, Ganchao and Chen, Jinze and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\n    journal={Optics Express},\n    volume={32},\n    number={11},\n    pages={18527--18538},\n    year={2024},\n    publisher={Optica Publishing Group}\n    }"
    },
    {
      "id": "deng2023prioritized",
      "title": "Prioritized Local Matching Network for Cross-Category Few-Shot Anomaly Detection",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/10494062",
      "authors": [
        "Huilin Deng",
        "Hongchen Luo",
        "Wei Zhai",
        "Yang Cao",
        "Yanming Guo",
        "Yu Kang"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/10494062",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/deng2023priorited.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-AI</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{deng2024prioritized,\n    title={Prioritized Local Matching Network for Cross-Category Few-Shot Anomaly Detection},\n    author={Deng, Huilin and Luo, Hongchen and Zhai, Wei and Cao, Yang and Kang, Yu},\n    journal={IEEE Transactions on Artificial Intelligence},\n    year={2024},\n    publisher={IEEE}\n    }"
    },
    {
      "id": "yang2023lemon",
      "title": "LEMON: Learning 3D Human-Object Interaction Relation from 2D Images",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2024/papers/Yang_LEMON_Learning_3D_Human-Object_Interaction_Relation_from_2D_Images_CVPR_2024_paper.pdf",
      "authors": [
        "Yuhang Yang",
        "Wei Zhai*",
        "Hongchen Luo",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/CVPR2024/papers/Yang_LEMON_Learning_3D_Human-Object_Interaction_Relation_from_2D_Images_CVPR_2024_paper.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/yang2023lemon.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2024</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{yang2024lemon,\n    title={LEMON: Learning 3D Human-Object Interaction Relation from 2D Images},\n    author={Yang, Yuhang and Zhai, Wei and Luo, Hongchen and Cao, Yang and Zha, Zheng-Jun},\n    booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},\n    pages={16284--16295},\n    year={2024}\n    }"
    },
    {
      "id": "wang2024mambapupil",
      "title": "Mambapupil: Bidirectional Selective Recurrent Model for Event-based Eye Tracking",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2024W/AI4Streaming/papers/Wang_MambaPupil_Bidirectional_Selective_Recurrent_Model_for_Event-based_Eye_Tracking_CVPRW_2024_paper.pdf",
      "authors": [
        "Zhong Wang",
        "Zengyu Wan",
        "Han Han",
        "Bohao Liao",
        "Yuliang Wu",
        "Wei Zhai*",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": "1st place challenge",
      "pdf": "https://openaccess.thecvf.com/content/CVPR2024W/AI4Streaming/papers/Wang_MambaPupil_Bidirectional_Selective_Recurrent_Model_for_Event-based_Eye_Tracking_CVPRW_2024_paper.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wang2024mambapupil.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2024 Workshop</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{wang2024mambapupil,\n    title={Mambapupil: Bidirectional selective recurrent model for event-based eye tracking},\n    author={Wang, Zhong and Wan, Zengyu and Han, Han and Liao, Bohao and Wu, Yuliang and Zhai, Wei and Cao, Yang and Zha, Zheng-jun},\n    booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},\n    pages={5762--5770},\n    year={2024}\n    }"
    },
    {
      "id": "liang2023hypercorrelation",
      "title": "Hypercorrelation Evolution for Video Class-Incremental Learning",
      "title_url": "https://ojs.aaai.org/index.php/AAAI/article/download/28117/28238",
      "authors": [
        "Sen Liang",
        "Kai Zhu*",
        "Zhiheng Liu",
        "Wei Zhai*",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2024,
      "section": "2024",
      "featured": false,
      "rating": null,
      "pdf": "https://ojs.aaai.org/index.php/AAAI/article/download/28117/28238",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/liang2023hypercorrelation.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">AAAI 2024</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{liang2024hypercorrelation,\n    title={Hypercorrelation Evolution for Video Class-Incremental Learning},\n    author={Liang, Sen and Zhu, Kai and Zhai, Wei and Liu, Zhiheng and Cao, Yang},\n    booktitle={Proceedings of the AAAI Conference on Artificial Intelligence},\n    volume={38},\n    number={4},\n    pages={3315--3323},\n    year={2024}\n    }"
    },
    {
      "id": "luo2022grounded",
      "title": "Grounded Affordance from Exocentric View",
      "title_url": "https://link.springer.com/article/10.1007/s11263-023-01962-z",
      "authors": [
        "Hongchen Luo",
        "Wei Zhai",
        "Jing Zhang",
        "Yang Cao",
        "Dacheng Tao"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://link.springer.com/article/10.1007/s11263-023-01962-z",
      "project": "",
      "code": "https://github.com/lhc1224/Cross-View-AG",
      "image": "./Wei Zhai_files/luo2022grounded.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">International Journal of Computer Vision (IJCV)</span>\n            <br><span class=\"paper-note\">Journal version of \"Learning Affordance Grounding from Exocentric Images\" (CVPR 2022)</span>",
      "note": "Journal version of \"Learning Affordance Grounding from Exocentric Images\" (CVPR 2022)",
      "description": "",
      "bibtex": "@article{luo2024grounded,\n    title={Grounded affordance from exocentric view},\n    author={Luo, Hongchen and Zhai, Wei and Zhang, Jing and Cao, Yang and Tao, Dacheng},\n    journal={International Journal of Computer Vision},\n    volume={132},\n    number={6},\n    pages={1945--1969},\n    year={2024},\n    publisher={Springer}\n    }"
    },
    {
      "id": "zhai2021on",
      "title": "On Exploring Multiplicity of Primitives and Attributes for Texture Recognition in the Wild",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/10286884/",
      "authors": [
        "Wei Zhai",
        "Yang Cao",
        "Jing Zhang",
        "Haiyong Xie",
        "Dacheng Tao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/10286884/",
      "project": "",
      "code": "https://github.com/tiaotiao11-22/MPAP",
      "image": "./Wei Zhai_files/zhai2021on.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-PAMI</span>\n            <br><span class=\"paper-note\">Journal version of MPAP (ICCV 2019) and DSR-Net (CVPR 2020)</span>",
      "note": "Journal version of MPAP (ICCV 2019) and DSR-Net (CVPR 2020)",
      "description": "",
      "bibtex": "@article{zhai2023exploring,\n    title={On exploring multiplicity of primitives and attributes for texture recognition in the wild},\n    author={Zhai, Wei and Cao, Yang and Zhang, Jing and Xie, Haiyong and Tao, Dacheng and Zha, Zheng-Jun},\n    journal={IEEE Transactions on Pattern Analysis and Machine Intelligence},\n    year={2023},\n    publisher={IEEE}\n    }"
    },
    {
      "id": "zhai2022background",
      "title": "Background Activation Suppression for Weakly Supervised Object Localization and Semantic Segmentation",
      "title_url": "https://link.springer.com/article/10.1007/s11263-023-01919-2",
      "authors": [
        "Wei Zhai",
        "Pingyu Wu",
        "Kai Zhu",
        "Yang Cao",
        "Feng Wu",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://link.springer.com/article/10.1007/s11263-023-01919-2",
      "project": "",
      "code": "https://github.com/wpy1999/BAS-Extension",
      "image": "./Wei Zhai_files/zhai2022background.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">International Journal of Computer Vision (IJCV)</span>\n            <br><span class=\"paper-note\">Journal version of BAS (CVPR 2022)</span>",
      "note": "Journal version of BAS (CVPR 2022)",
      "description": "",
      "bibtex": "@article{zhai2024background,\n    title={Background activation suppression for weakly supervised object localization and semantic segmentation},\n    author={Zhai, Wei and Wu, Pingyu and Zhu, Kai and Cao, Yang and Wu, Feng and Zha, Zheng-Jun},\n    journal={International Journal of Computer Vision},\n    volume={132},\n    number={3},\n    pages={750--775},\n    year={2024},\n    publisher={Springer}\n    }"
    },
    {
      "id": "luo2021learning",
      "title": "Learning Visual Affordance Grounding from Demonstration Videos",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/10246333/",
      "authors": [
        "Hongchen Luo",
        "Wei Zhai",
        "Jing Zhang",
        "Yang Cao",
        "Dacheng Tao"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/10246333/",
      "project": "",
      "code": "https://github.com/lhc1224/HAG-Net",
      "image": "./Wei Zhai_files/luo2021learning.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-NNLS</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{luo2023learning,\n    title={Learning visual affordance grounding from demonstration videos},\n    author={Luo, Hongchen and Zhai, Wei and Zhang, Jing and Cao, Yang and Tao, Dacheng},\n    journal={IEEE Transactions on Neural Networks and Learning Systems},\n    year={2023},\n    publisher={IEEE}\n    }"
    },
    {
      "id": "wu2023spatial",
      "title": "Spatial-Aware Token for Weakly Supervised Object Localization",
      "title_url": "https://openaccess.thecvf.com/content/ICCV2023/papers/Wu_Spatial-Aware_Token_for_Weakly_Supervised_Object_Localization_ICCV_2023_paper.pdf",
      "authors": [
        "Pingyu Wu",
        "Wei Zhai*",
        "Yang Cao",
        "Jiebo Luo",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/ICCV2023/papers/Wu_Spatial-Aware_Token_for_Weakly_Supervised_Object_Localization_ICCV_2023_paper.pdf",
      "project": "",
      "code": "https://github.com/wpy1999/SAT",
      "image": "./Wei Zhai_files/wu2023spatial.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICCV 2023</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{wu2023spatial,\n    title={Spatial-aware token for weakly supervised object localization},\n    author={Wu, Pingyu and Zhai, Wei and Cao, Yang and Luo, Jiebo and Zha, Zheng-Jun},\n    booktitle={Proceedings of the IEEE/CVF International Conference on Computer Vision},\n    pages={1844--1854},\n    year={2023}\n    }"
    },
    {
      "id": "yang2023grounding",
      "title": "Grounding 3D Object Affordance from 2D Interactions in Images",
      "title_url": "https://openaccess.thecvf.com/content/ICCV2023/papers/Yang_Grounding_3D_Object_Affordance_from_2D_Interactions_in_Images_ICCV_2023_paper.pdf",
      "authors": [
        "Yuhang Yang",
        "Wei Zhai*",
        "Hongchen Luo",
        "Yang Cao",
        "Jiebo Luo",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/ICCV2023/papers/Yang_Grounding_3D_Object_Affordance_from_2D_Interactions_in_Images_ICCV_2023_paper.pdf",
      "project": "",
      "code": "https://github.com/yyvhang/IAGNet",
      "image": "./Wei Zhai_files/yang2023grounding.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICCV 2023</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{yang2023grounding,\n    title={Grounding 3d object affordance from 2d interactions in images},\n    author={Yang, Yuhang and Zhai, Wei and Luo, Hongchen and Cao, Yang and Luo, Jiebo and Zha, Zheng-Jun},\n    booktitle={Proceedings of the IEEE/CVF International Conference on Computer Vision},\n    pages={10905--10915},\n    year={2023}\n    }"
    },
    {
      "id": "wang2023robustness",
      "title": "Robustness Benchmark for Unsupervised Anomaly Detection Models",
      "title_url": "https://just.ustc.edu.cn/en/article/doi/10.52396/JUSTC-2022-0165",
      "authors": [
        "Pei Wang",
        "Wei Zhai",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://just.ustc.edu.cn/en/article/doi/10.52396/JUSTC-2022-0165",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wang2023robustness.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">Journal of University of Science and Technology of China (JUSTC)</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wang2024robustness,\n    title={Robustness benchmark for unsupervised anomaly detection models},\n    author={Wang, Pei and Zhai, Wei and Cao, Yang},\n    journal={JUSTC},\n    volume={54},\n    number={1},\n    pages={0103--1},\n    year={2024},\n    publisher={JUSTC}\n    }"
    },
    {
      "id": "luo2023leverage",
      "title": "Leverage Interactive Affinity for Affordance Learning",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2023/papers/Luo_Leverage_Interactive_Affinity_for_Affordance_Learning_CVPR_2023_paper.pdf",
      "authors": [
        "Hongchen Luo#",
        "Wei Zhai#",
        "Jing Zhang",
        "Yang Cao",
        "Dacheng Tao"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/CVPR2023/papers/Luo_Leverage_Interactive_Affinity_for_Affordance_Learning_CVPR_2023_paper.pdf",
      "project": "",
      "code": "https://github.com/lhc1224/PIAL-Net",
      "image": "./Wei Zhai_files/luo2023leverage.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2023</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{luo2023leverage,\n    title={Leverage interactive affinity for affordance learning},\n    author={Luo, Hongchen and Zhai, Wei and Zhang, Jing and Cao, Yang and Tao, Dacheng},\n    booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},\n    pages={6809--6819},\n    year={2023}\n    }"
    },
    {
      "id": "lu2023uncertainty",
      "title": "Uncertainty-Aware Optimal Transport for Semantically Coherent Out-of-Distribution Detection",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2023/papers/Lu_Uncertainty-Aware_Optimal_Transport_for_Semantically_Coherent_Out-of-Distribution_Detection_CVPR_2023_paper.pdf",
      "authors": [
        "Fan Lu",
        "Kai Zhu",
        "Wei Zhai",
        "Kecheng Zheng",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/CVPR2023/papers/Lu_Uncertainty-Aware_Optimal_Transport_for_Semantically_Coherent_Out-of-Distribution_Detection_CVPR_2023_paper.pdf",
      "project": "",
      "code": "https://github.com/LuFan31/ET-OOD",
      "image": "./Wei Zhai_files/lu2023uncertainty.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2023</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{lu2023uncertainty,\n    title={Uncertainty-Aware Optimal Transport for Semantically Coherent Out-of-Distribution Detection},\n    author={Lu, Fan and Zhu, Kai and Zhai, Wei and Zheng, Kecheng and Cao, Yang},\n    booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},\n    pages={3282--3291},\n    year={2023}\n    }"
    },
    {
      "id": "dong2023exploring",
      "title": "Exploring Tuning Characteristics of Ventral Stream's Neurons for Few-Shot Image Classification",
      "title_url": "https://ojs.aaai.org/index.php/AAAI/article/download/25128/24900",
      "authors": [
        "Lintao Dong",
        "Wei Zhai",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2023,
      "section": "2023",
      "featured": false,
      "rating": "oral",
      "pdf": "https://ojs.aaai.org/index.php/AAAI/article/download/25128/24900",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/dong2023exploring.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">AAAI 2023</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{dong2023exploring,\n    title={Exploring Tuning Characteristics of Ventral Stream’s Neurons for Few-Shot Image Classification},\n    author={Dong, Lintao and Zhai, Wei and Zha, Zheng-Jun},\n    booktitle={Proceedings of the AAAI Conference on Artificial Intelligence},\n    volume={37},\n    number={1},\n    pages={534--542},\n    year={2023}\n    }"
    },
    {
      "id": "zhai2022exploring",
      "title": "Exploring Figure-Ground Assignment Mechanism in Perceptual Organization",
      "title_url": "https://proceedings.neurips.cc/paper_files/paper/2022/file/6cc31b44d88dce8380d36e81485cd07f-Paper-Conference.pdf",
      "authors": [
        "Wei Zhai",
        "Yang Cao",
        "Jing Zhang",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://proceedings.neurips.cc/paper_files/paper/2022/file/6cc31b44d88dce8380d36e81485cd07f-Paper-Conference.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhai2022exploring.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">NeurIPS 2022</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{zhai2022exploring,\n    title={Exploring figure-ground assignment mechanism in perceptual organization},\n    author={Zhai, Wei and Cao, Yang and Zhang, Jing and Zha, Zheng-Jun},\n    journal={Advances in Neural Information Processing Systems},\n    volume={35},\n    pages={17030--17042},\n    year={2022}\n    }"
    },
    {
      "id": "lu2022phrase",
      "title": "Phrase-Based Affordance Detection via Cyclic Bilateral Interaction",
      "title_url": "https://proceedings.neurips.cc/paper_files/paper/2022/file/6cc31b44d88dce8380d36e81485cd07f-Paper-Conference.pdf",
      "authors": [
        "Liangsheng Lu#",
        "Wei Zhai#",
        "Hongchen Luo",
        "Kang Yu",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://proceedings.neurips.cc/paper_files/paper/2022/file/6cc31b44d88dce8380d36e81485cd07f-Paper-Conference.pdf",
      "project": "",
      "code": "https://github.com/lulsheng/CBCE-Net",
      "image": "./Wei Zhai_files/lu2022phrase.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-AI</span>",
      "note": "",
      "description": "",
      "bibtex": ""
    },
    {
      "id": "zhai2022one",
      "title": "One-Shot Affordance Detection in the Wild",
      "title_url": "https://link.springer.com/article/10.1007/s11263-022-01642-4",
      "authors": [
        "Wei Zhai#",
        "Hongchen Luo#",
        "Jing Zhang",
        "Yang Cao",
        "Dacheng Tao"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://link.springer.com/article/10.1007/s11263-022-01642-4",
      "project": "",
      "code": "https://github.com/lhc1224/OSAD_Net",
      "image": "./Wei Zhai_files/zhai2022one.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">International Journal of Computer Vision (IJCV)</span>\n            <br><span class=\"paper-note\">Journal version of \"One-Shot Affordance Detection\" (IJCAI 2021)</span>",
      "note": "Journal version of \"One-Shot Affordance Detection\" (IJCAI 2021)",
      "description": "",
      "bibtex": "@article{zhai2022one,\n    title={One-shot object affordance detection in the wild},\n    author={Zhai, Wei and Luo, Hongchen and Zhang, Jing and Cao, Yang and Tao, Dacheng},\n    journal={International Journal of Computer Vision},\n    volume={130},\n    number={10},\n    pages={2472--2500},\n    year={2022},\n    publisher={Springer}\n    }"
    },
    {
      "id": "zhai2022deep",
      "title": "Deep Texton-Coherence Network for Camouflaged Object Detection",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/9815160",
      "authors": [
        "Wei Zhai",
        "Yang Cao",
        "Haiyong Xie",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/9815160",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhai2022deep.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-MM</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{zhai2022deep,\n    title={Deep texton-coherence network for camouflaged object detection},\n    author={Zhai, Wei and Cao, Yang and Xie, HaiYong and Zha, Zheng-Jun},\n    journal={IEEE Transactions on Multimedia},\n    year={2022},\n    publisher={IEEE}\n    }"
    },
    {
      "id": "li2022location",
      "title": "Location-Free Camouflage Generation Network",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/9817812",
      "authors": [
        "Yangyang Li#",
        "Wei Zhai#",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/9817812",
      "project": "",
      "code": "https://github.com/Tale17/LCG-Net",
      "image": "./Wei Zhai_files/li2022location.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-MM</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{li2022location,\n    title={Location-free camouflage generation network},\n    author={Li, Yangyang and Zhai, Wei and Cao, Yang and Zha, Zheng-jun},\n    journal={IEEE Transactions on Multimedia},\n    year={2022},\n    publisher={IEEE}\n    }"
    },
    {
      "id": "luo2022learning",
      "title": "Learning Affordance Grounding from Exocentric Images",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2022/papers/Luo_Learning_Affordance_Grounding_From_Exocentric_Images_CVPR_2022_paper.pdf",
      "authors": [
        "Hongchen Luo#",
        "Wei Zhai#",
        "Jing Zhang",
        "Yang Cao",
        "Dacheng Tao"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/CVPR2022/papers/Luo_Learning_Affordance_Grounding_From_Exocentric_Images_CVPR_2022_paper.pdf",
      "project": "",
      "code": "https://github.com/lhc1224/Cross-View-AG",
      "image": "./Wei Zhai_files/luo2022learning.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2022</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{luo2022learning,\n    title={Learning affordance grounding from exocentric images},\n    author={Luo, Hongchen and Zhai, Wei and Zhang, Jing and Cao, Yang and Tao, Dacheng},\n    booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},\n    pages={2252--2261},\n    year={2022}\n    }"
    },
    {
      "id": "wu2022background",
      "title": "Background Activation Suppression for Weakly Supervised Object Localization",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2022/papers/Wu_Background_Activation_Suppression_for_Weakly_Supervised_Object_Localization_CVPR_2022_paper.pdf",
      "authors": [
        "Pingyu Wu#",
        "Wei Zhai#",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/CVPR2022/papers/Wu_Background_Activation_Suppression_for_Weakly_Supervised_Object_Localization_CVPR_2022_paper.pdf",
      "project": "",
      "code": "https://github.com/wpy1999/BAS",
      "image": "./Wei Zhai_files/wu2022background.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2022</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{wu2022background,\n    title={Background activation suppression for weakly supervised object localization},\n    author={Wu, Pingyu and Zhai, Wei and Cao, Yang},\n    booktitle={2022 IEEE/CVF Conference on Computer Vision and Pattern Recognition (CVPR)},\n    pages={14228--14237},\n    year={2022},\n    organization={IEEE}\n    }"
    },
    {
      "id": "zhu2022self",
      "title": "Self-Sustaining Representation Expansion for Non-Exemplar Class-Incremental Learnings",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2022/papers/Zhu_Self-Sustaining_Representation_Expansion_for_Non-Exemplar_Class-Incremental_Learning_CVPR_2022_paper.pdf",
      "authors": [
        "Kai Zhu",
        "Wei Zhai",
        "Yang Cao",
        "Jiebo Luo",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/CVPR2022/papers/Zhu_Self-Sustaining_Representation_Expansion_for_Non-Exemplar_Class-Incremental_Learning_CVPR_2022_paper.pdf",
      "project": "",
      "code": "https://github.com/zhukaii/SSRE",
      "image": "./Wei Zhai_files/zhu2022self.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2022</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{zhu2022self,\n    title={Self-sustaining representation expansion for non-exemplar class-incremental learning},\n    author={Zhu, Kai and Zhai, Wei and Cao, Yang and Luo, Jiebo and Zha, Zheng-Jun},\n    booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},\n    pages={9296--9305},\n    year={2022}\n    }"
    },
    {
      "id": "wang2022robust",
      "title": "Robust Object Detection via Adversarial Novel Style Exploration",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/9697984",
      "authors": [
        "Wen Wang",
        "Jing Zhang",
        "Wei Zhai",
        "Yang Cao",
        "Dacheng Tao"
      ],
      "me": "Wei Zhai",
      "year": 2022,
      "section": "2022",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/9697984",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wang2022robust.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-IP</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wang2022robust,\n    title={Robust object detection via adversarial novel style exploration},\n    author={Wang, Wen and Zhang, Jing and Zhai, Wei and Cao, Yang and Tao, Dacheng},\n    journal={IEEE Transactions on Image Processing},\n    volume={31},\n    pages={1949--1962},\n    year={2022},\n    publisher={IEEE}\n    }"
    },
    {
      "id": "luo2021one",
      "title": "One-Shot Affordance Detection",
      "title_url": "https://www.ijcai.org/proceedings/2021/0124.pdf",
      "authors": [
        "Hongchen Luo",
        "Wei Zhai",
        "Jing Zhang",
        "Yang Cao",
        "Dacheng Tao"
      ],
      "me": "Wei Zhai",
      "year": 2021,
      "section": "2021",
      "featured": false,
      "rating": "oral",
      "pdf": "https://www.ijcai.org/proceedings/2021/0124.pdf",
      "project": "",
      "code": "https://github.com/lhc1224/OSAD_Net",
      "image": "./Wei Zhai_files/luo2021one.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IJCAI 2021</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{luo2021one,\n    title={One-shot affordance detection},\n    author={Luo, Hongchen and Zhai, Wei and Zhang, Jing and Cao, Yang and Tao, Dacheng},\n    journal={arXiv preprint arXiv:2106.14747},\n    year={2021}\n    }"
    },
    {
      "id": "li2021tri",
      "title": "A Tri-Attention Enhanced Graph Convolutional Network for Skeleton-Based Action Recognition",
      "title_url": "https://ietresearch.onlinelibrary.wiley.com/doi/pdfdirect/10.1049/cvi2.12017",
      "authors": [
        "Xingming Li",
        "Wei Zhai",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2021,
      "section": "2021",
      "featured": false,
      "rating": null,
      "pdf": "https://ietresearch.onlinelibrary.wiley.com/doi/pdfdirect/10.1049/cvi2.12017",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/li2021tri.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IET Computer Vision (IET-CV 2021)</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{li2021tri,\n    title={A tri-attention enhanced graph convolutional network for skeleton-based action recognition},\n    author={Li, Xingming and Zhai, Wei and Cao, Yang},\n    journal={IET Computer Vision},\n    volume={15},\n    number={2},\n    pages={110--121},\n    year={2021},\n    publisher={Wiley Online Library}\n    }"
    },
    {
      "id": "zhu2021self",
      "title": "Self-Promoted Prototype Refinement for Few-Shot Class-Incremental Learning",
      "title_url": "https://openaccess.thecvf.com/content/CVPR2021/papers/Zhu_Self-Promoted_Prototype_Refinement_for_Few-Shot_Class-Incremental_Learning_CVPR_2021_paper.pdf",
      "authors": [
        "Kai Zhu",
        "Yang Cao",
        "Wei Zhai",
        "Jie Cheng",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2021,
      "section": "2021",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content/CVPR2021/papers/Zhu_Self-Promoted_Prototype_Refinement_for_Few-Shot_Class-Incremental_Learning_CVPR_2021_paper.pdf",
      "project": "",
      "code": "https://github.com/zhukaii/SPPR",
      "image": "./Wei Zhai_files/zhu2021self.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2021</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{zhu2021self,\n    title={Self-promoted prototype refinement for few-shot class-incremental learning},\n    author={Zhu, Kai and Cao, Yang and Zhai, Wei and Cheng, Jie and Zha, Zheng-Jun},\n    booktitle={Proceedings of the IEEE/CVF conference on computer vision and pattern recognition},\n    pages={6801--6810},\n    year={2021}\n    }"
    },
    {
      "id": "zhu2020self",
      "title": "Self-Supervised Tuning for Few-Shot Segmentation",
      "title_url": "https://www.ijcai.org/proceedings/2020/0142.pdf",
      "authors": [
        "Kai Zhu",
        "Wei Zhai",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2020,
      "section": "2020",
      "featured": false,
      "rating": "oral",
      "pdf": "https://www.ijcai.org/proceedings/2020/0142.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhu2020self.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IJCAI 2020</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{zhu2021self,\n    title={Self-supervised tuning for few-shot segmentation},\n    author={Zhu, Kai and Zhai, Wei and Cao, Yang},\n    booktitle={Proceedings of the Twenty-Ninth International Conference on International Joint Conferences on Artificial Intelligence},\n    pages={1019--1025},\n    year={2021}\n    }"
    },
    {
      "id": "wang2020deep",
      "title": "Deep Inhomogeneous Regularization for Transfer Learning",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/9190822",
      "authors": [
        "Wen Wang",
        "Wei Zhai",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2020,
      "section": "2020",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/9190822",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wang2020deep.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICIP 2020</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{wang2020deep,\n    title={Deep inhomogeneous regularization for transfer learning},\n    author={Wang, Wen and Zhai, Wei and Cao, Yang},\n    booktitle={2020 IEEE International Conference on Image Processing (ICIP)},\n    pages={221--225},\n    year={2020},\n    organization={IEEE}\n    }"
    },
    {
      "id": "zhai2020deep",
      "title": "Deep Structure-Revealed Network for Texture Recognition",
      "title_url": "https://openaccess.thecvf.com/content_CVPR_2020/papers/Zhai_Deep_Structure-Revealed_Network_for_Texture_Recognition_CVPR_2020_paper.pdf",
      "authors": [
        "Wei Zhai",
        "Yang Cao",
        "Zheng-Jun Zha",
        "HaiYong Xie",
        "Feng Wu"
      ],
      "me": "Wei Zhai",
      "year": 2020,
      "section": "2020",
      "featured": false,
      "rating": "oral",
      "pdf": "https://openaccess.thecvf.com/content_CVPR_2020/papers/Zhai_Deep_Structure-Revealed_Network_for_Texture_Recognition_CVPR_2020_paper.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhai2020deep.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">CVPR 2020</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{zhai2020deep,\n    title={Deep structure-revealed network for texture recognition},\n    author={Zhai, Wei and Cao, Yang and Zha, Zheng-Jun and Xie, HaiYong and Wu, Feng},\n    booktitle={Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition},\n    pages={11010--11019},\n    year={2020}\n    }"
    },
    {
      "id": "zhu2020one",
      "title": "One-Shot Texture Retrieval Using Global Grouping Metric",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/9224176",
      "authors": [
        "Kai Zhu",
        "Yang Cao",
        "Wei Zhai",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2020,
      "section": "2020",
      "featured": false,
      "rating": null,
      "pdf": "https://ieeexplore.ieee.org/abstract/document/9224176",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhu2020one.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IEEE T-MM 2020</span>\n            <br><span class=\"paper-note\">Journal version of \"One-Shot Texture Retrieval with Global Context Metric\" (IJCAI 2019)</span>",
      "note": "Journal version of \"One-Shot Texture Retrieval with Global Context Metric\" (IJCAI 2019)",
      "description": "",
      "bibtex": "@article{zhu2020one,\n    title={One-shot texture retrieval using global grouping metric},\n    author={Zhu, Kai and Cao, Yang and Zhai, Wei and Zha, Zheng-Jun},\n    journal={IEEE Transactions on Multimedia},\n    volume={23},\n    pages={3726--3737},\n    year={2020},\n    publisher={IEEE}\n    }"
    },
    {
      "id": "zhai2019deep",
      "title": "Deep Multiple-Attribute-Perceived Network for Real-World Texture Recognition",
      "title_url": "https://openaccess.thecvf.com/content_ICCV_2019/papers/Zhai_Deep_Multiple-Attribute-Perceived_Network_for_Real-World_Texture_Recognition_ICCV_2019_paper.pdf",
      "authors": [
        "Wei Zhai",
        "Yang Cao",
        "Jing Zhang",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2019,
      "section": "2019",
      "featured": false,
      "rating": null,
      "pdf": "https://openaccess.thecvf.com/content_ICCV_2019/papers/Zhai_Deep_Multiple-Attribute-Perceived_Network_for_Real-World_Texture_Recognition_ICCV_2019_paper.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhai2019deep.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICCV 2019</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{zhai2019deep,\n    title={Deep multiple-attribute-perceived network for real-world texture recognition},\n    author={Zhai, Wei and Cao, Yang and Zhang, Jing and Zha, Zheng-Jun},\n    booktitle={Proceedings of the IEEE/CVF International Conference on Computer Vision},\n    pages={3613--3622},\n    year={2019}\n    }"
    },
    {
      "id": "zhu2019one",
      "title": "One-Shot Texture Retrieval with Global Context Metric",
      "title_url": "https://arxiv.org/pdf/1905.06656.pdf",
      "authors": [
        "Kai Zhu",
        "Wei Zhai",
        "Zheng-Jun Zha",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2019,
      "section": "2019",
      "featured": false,
      "rating": "oral",
      "pdf": "https://arxiv.org/pdf/1905.06656.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhu2019one.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IJCAI 2019</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{zhu2019one,\n    title={One-shot texture retrieval with global context metric},\n    author={Zhu, Kai and Zhai, Wei and Zha, Zheng-Jun and Cao, Yang},\n    journal={arXiv preprint arXiv:1905.06656},\n    year={2019}\n    }"
    },
    {
      "id": "wu2019pixtextgan",
      "title": "PixTextGAN: Structure Aware Text Image Synthesis for License Plate Recognition",
      "title_url": "https://ietresearch.onlinelibrary.wiley.com/doi/pdfdirect/10.1049/iet-ipr.2018.6588",
      "authors": [
        "Shilian Wu",
        "Wei Zhai",
        "Yang Cao"
      ],
      "me": "Wei Zhai",
      "year": 2019,
      "section": "2019",
      "featured": false,
      "rating": null,
      "pdf": "https://ietresearch.onlinelibrary.wiley.com/doi/pdfdirect/10.1049/iet-ipr.2018.6588",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/wu2019pixtextgan.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">IET Image Processing (IET-IP 2019)</span>",
      "note": "",
      "description": "",
      "bibtex": "@article{wu2019pixtextgan,\n    title={PixTextGAN: structure aware text image synthesis for license plate recognition},\n    author={Wu, Shilian and Zhai, Wei and Cao, Yang},\n    journal={IET Image Processing},\n    volume={13},\n    number={14},\n    pages={2744--2752},\n    year={2019},\n    publisher={Wiley Online Library}\n    }"
    },
    {
      "id": "zhai2018generative",
      "title": "A Generative Adversarial Network Based Framework for Unsupervised Visual Surface Inspection",
      "title_url": "https://ieeexplore.ieee.org/abstract/document/8462364",
      "authors": [
        "Wei Zhai",
        "Jiang Zhu",
        "Yang Cao",
        "Zengfu Wang"
      ],
      "me": "Wei Zhai",
      "year": 2018,
      "section": "2018",
      "featured": false,
      "rating": "oral",
      "pdf": "https://ieeexplore.ieee.org/abstract/document/8462364",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhai2018generative.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">ICASSP 2018</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{zhai2018generative,\n    title={A generative adversarial network based framework for unsupervised visual surface inspection},\n    author={Zhai, Wei and Zhu, Jiang and Cao, Yang and Wang, Zengfu},\n    booktitle={2018 IEEE International Conference on Acoustics, Speech and Signal Processing (ICASSP)},\n    pages={1283--1287},\n    year={2018},\n    organization={IEEE}\n    }"
    },
    {
      "id": "zhu2018co",
      "title": "Co-Occurrent Structural Edge Detection for Color-Guided Depth Map Super-Resolution",
      "title_url": "https://link.springer.com/content/pdf/10.1007%2F978-3-319-73603-7_8.pdf",
      "authors": [
        "Jiang Zhu",
        "Wei Zhai",
        "Yang Cao",
        "Zheng-Jun Zha"
      ],
      "me": "Wei Zhai",
      "year": 2018,
      "section": "2018",
      "featured": false,
      "rating": "oral",
      "pdf": "https://link.springer.com/content/pdf/10.1007%2F978-3-319-73603-7_8.pdf",
      "project": "",
      "code": "",
      "image": "./Wei Zhai_files/zhu2018co.png",
      "video": "",
      "venue_html": "In <span class=\"venue-name\">MMM 2018</span>",
      "note": "",
      "description": "",
      "bibtex": "@inproceedings{zhu2018co,\n    title={Co-occurrent structural edge detection for color-guided depth map super-resolution},\n    author={Zhu, Jiang and Zhai, Wei and Cao, Yang and Zha, Zheng-Jun},\n    booktitle={MultiMedia Modeling: 24th International Conference, MMM 2018, Bangkok, Thailand, February 5-7, 2018, Proceedings, Part I 24},\n    pages={93--105},\n    year={2018},\n    organization={Springer}\n    }"
    }
  ]
};
